parameters:
    phumbor.url.builder_factory.class: Thumbor\Url\BuilderFactory
    phumbor.url.transformer.class: Jb\Bundle\PhumborBundle\Transformer\BaseTransformer

services:
    phumbor.url.builder_factory:
        class: %phumbor.url.builder_factory.class%
        arguments:
            - %phumbor.server.url%
            - %phumbor.secret%

    phumbor.url.transformer:
        class: %phumbor.url.transformer.class%
        arguments:
            - @phumbor.url.builder_factory
            - %phumbor.transformations%